backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

locale: 'fa'

collections:
  - name: "products"
    label: "محصولات"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "عنوان محصول", name: "title", widget: "string"}
      - {label: "توضیحات", name: "body", widget: "markdown"}
      - {label: "تصویر", name: "image", widget: "image"}
      - {label: "قیمت", name: "price", widget: "string"}
